language: go

go:
  - 1.6

env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/tools/godep
  - godep restore
  - go get github.com/mitchellh/gox
  - gox
  - go get github.com/tcnksm/ghr
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/